from flask import Flask
# THIS BOC IS CREATING AN OBJ THAT WILL REPRESENT THE WEB APP CALLED APP
app = Flask(__name__)

# THIS BOC DEFINES THE ROUTES OF THE WEBSITE *** THIS IS CALLED A DECORATOR ***
# ROUTES ARE WHAT WE TYPE IN THE BROWSER TO GO TO DIFFERENT PAGES
# YOU CAN HAVE A ROUTE FOR THE HOME-PAGE, THE ABOUT PAGE AND OTHER PAGES
# WITHIN YOUR WEB SITE
# THIS ROUTE WILL DEFINE THE HOME PAGE
@app.route("/")

# YOU CAN HAVE MULTIPLE ROUTES GOING TO THE SAME WEB PAGE
#BELOW IS A ROUTE ADDED SO IF THE USER APPEND "/home" AT THE END OF THE URL
# IT WILL GO TO THE SAME WEB PAGE AS THE USER JUST TYPING THE URL
# GLITCH.COM & GLITCH.COM/HOME WILL TAKE YOU TO THE SAME HOME-PAGE
# @app.route("/home")
def home():
    # THE HOME PAGE IS WRAPPED IN HTML TAGS
    return "<h1>THE MOTHERFUCKING SHIT BRO</h1>"

# THIS ROUTE WILL DEFINE THE ABOUT PAGE
@app.route("/about")
def about():
    return "<h1>About Page</h1>"


if __name__ == '__main__':
    app.run(debug=True)

